apps/authentication/models.py
from flask_login import UserMixin

from apps import db, login_manager

from apps.authentication.util import hash_pass

class Users(db.Model, UserMixin):

    __tablename__ = 'Users'

    id = db.Column(db.Integer, primary_key=True)
    username = db.Column(db.String(64), unique=True)
    email = db.Column(db.String(64), unique=True)
    password = db.Column(db.LargeBinary)

    def __init__(self, **kwargs):
        for property, value in kwargs.items():
            # depending on whether value is an iterable or not, we must
            # unpack it's value (when **kwargs is request.form, some values
            # will be a 1-element list)
            if hasattr(value, '__iter__') and not isinstance(value, str):
                # the ,= unpack of a singleton fails PEP8 (travis flake8 test)
                value = value[0]

            if property == 'password':
                value = hash_pass(value)  # we need bytes here (not plain str)

            setattr(self, property, value)

    def __repr__(self):
        return str(self.username)


@login_manager.user_loader
def user_loader(id):
    return Users.query.filter_by(id=id).first()


@login_manager.request_loader
def request_loader(request):
    username = request.form.get('username')
    user = Users.query.filter_by(username=username).first()
    return user if user else None

apps/authentication/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, PasswordField
from wtforms.validators import Email, DataRequired

# login and registration


class LoginForm(FlaskForm):
    username = StringField('Username',
                         id='username_login',
                         validators=[DataRequired()])
    password = PasswordField('Password',
                             id='pwd_login',
                             validators=[DataRequired()])


class CreateAccountForm(FlaskForm):
    username = StringField('Username',
                         id='username_create',
                         validators=[DataRequired()])
    email = StringField('Email',
                      id='email_create',
                      validators=[DataRequired(), Email()])
    password = PasswordField('Password',
                             id='pwd_create',
                             validators=[DataRequired()])

apps/__init__.py
# -*- encoding: utf-8 -*-
"""
Copyright (c) 2019 - present AppSeed.us
"""

import os

from flask import Flask
from flask_login import LoginManager
from flask_sqlalchemy import SQLAlchemy
from importlib import import_module


db = SQLAlchemy()
login_manager = LoginManager()


def register_extensions(app):
    db.init_app(app)
    login_manager.init_app(app)


def register_blueprints(app):
    for module_name in ('authentication', 'home'):
        module = import_module('apps.{}.routes'.format(module_name))
        app.register_blueprint(module.blueprint)


def configure_database(app):

    @app.before_first_request
    def initialize_database():
        try:
            db.create_all()
        except Exception as e:

            print('> Error: DBMS Exception: ' + str(e) )

            # fallback to SQLite
            basedir = os.path.abspath(os.path.dirname(__file__))
            app.config['SQLALCHEMY_DATABASE_URI'] = SQLALCHEMY_DATABASE_URI = 'sqlite:///' + os.path.join(basedir, 'db.sqlite3')

            print('> Fallback to SQLite ')
            db.create_all()

    @app.teardown_request
    def shutdown_session(exception=None):
        db.session.remove() 


def create_app(config):
    app = Flask(__name__)
    app.config.from_object(config)
    register_extensions(app)
    register_blueprints(app)
    configure_database(app)
    return app

apps/authentication/__init__.py
from flask import Blueprint

blueprint = Blueprint(
    'authentication_blueprint',
    __name__,
    url_prefix=''
)

apps/authentication/routes.py
from flask import render_template, redirect, request, url_for
from flask_login import (
    current_user,
    login_user,
    logout_user
)

from apps import db, login_manager
from apps.authentication import blueprint
from apps.authentication.forms import LoginForm, CreateAccountForm
from apps.authentication.models import Users

from apps.authentication.util import verify_pass


@blueprint.route('/')
def route_default():
    return redirect(url_for('authentication_blueprint.login'))


# Login & Registration

@blueprint.route('/login', methods=['GET', 'POST'])
def login():
    login_form = LoginForm(request.form)
    if 'login' in request.form:

        # read form data
        username = request.form['username']
        password = request.form['password']

        # Locate user
        user = Users.query.filter_by(username=username).first()

        # Check the password
        if user and verify_pass(password, user.password):

            login_user(user)
            return redirect(url_for('authentication_blueprint.route_default'))

        # Something (user or pass) is not ok
        return render_template('accounts/login.html',
                               msg='Wrong user or password',
                               form=login_form)

    if not current_user.is_authenticated:
        return render_template('accounts/login.html',
                               form=login_form)
    return redirect(url_for('home_blueprint.index'))


@blueprint.route('/register', methods=['GET', 'POST'])
def register():
    create_account_form = CreateAccountForm(request.form)
    if 'register' in request.form:

        username = request.form['username']
        email = request.form['email']

        # Check usename exists
        user = Users.query.filter_by(username=username).first()
        if user:
            return render_template('accounts/register.html',
                                   msg='Username already registered',
                                   success=False,
                                   form=create_account_form)

        # Check email exists
        user = Users.query.filter_by(email=email).first()
        if user:
            return render_template('accounts/register.html',
                                   msg='Email already registered',
                                   success=False,
                                   form=create_account_form)

        # else we can create the user
        user = Users(**request.form)
        db.session.add(user)
        db.session.commit()

        return render_template('accounts/register.html',
                               msg='User created please <a href="/login">login</a>',
                               success=True,
                               form=create_account_form)

    else:
        return render_template('accounts/register.html', form=create_account_form)


@blueprint.route('/logout')
def logout():
    logout_user()
    return redirect(url_for('authentication_blueprint.login'))


# Errors

@login_manager.unauthorized_handler
def unauthorized_handler():
    return render_template('home/page-403.html'), 403


@blueprint.errorhandler(403)
def access_forbidden(error):
    return render_template('home/page-403.html'), 403


@blueprint.errorhandler(404)
def not_found_error(error):
    return render_template('home/page-404.html'), 404


@blueprint.errorhandler(500)
def internal_error(error):
    return render_template('home/page-500.html'), 500

apps/home/__init__.py
from flask import Blueprint

blueprint = Blueprint(
    'home_blueprint',
    __name__,
    url_prefix=''
)

apps/home/routes.py
from apps.home import blueprint
from flask import render_template, request
from flask_login import login_required
from jinja2 import TemplateNotFound


@blueprint.route('/index')
@login_required
def index():

    return render_template('home/index.html', segment='index')


@blueprint.route('/<template>')
@login_required
def route_template(template):

    try:

        if not template.endswith('.html'):
            template += '.html'

        # Detect the current page
        segment = get_segment(request)

        # Serve the file (if exists) from app/templates/home/FILE.html
        return render_template("home/" + template, segment=segment)

    except TemplateNotFound:
        return render_template('home/page-404.html'), 404

    except:
        return render_template('home/page-500.html'), 500


# Helper - Extract current page name from request
def get_segment(request):

    try:

        segment = request.path.split('/')[-1]

        if segment == '':
            segment = 'index'

        return segment

    except:
        return None

apps/templates/accounts/login.html
{% extends "layouts/base-fullscreen.html" %}

{% block title %} Sign IN {% endblock %} 

<!-- Specific Page CSS goes HERE  -->
{% block stylesheets %}{% endblock stylesheets %}

{% block content %}

    <main>

        {% include 'includes/preloader.html' %}

        <!-- Section -->
        <section class="min-vh-100 d-flex align-items-center section-image overlay-soft-dark" data-background="/static/assets/img/pages/form-image.jpg">
            <div class="container">
                <div class="row justify-content-center">
                    <div class="col-12 d-flex align-items-center justify-content-center">
                        <div class="signin-inner my-4 my-lg-0 bg-white shadow-soft border rounded border-gray-300 p-4 p-lg-5 w-100 fmxw-500">
                            <div class="text-center text-md-center mb-4 mt-md-0">
                                <h1 class="mb-0 h3">
                                    <a href="https://appseed.us/product/pixel-bootstrap/flask/" target="_blank"> Nutriwizard</a> - Login
                                </h1>
                                <br />
                                <span class="font-weight-normal">
                                    {% if msg %}
                                        <span class="text-danger">
                                            {{ msg | safe }}
                                        </span>                                        
                                    {% else %}
                                        Ingresa tus credenciales
                                    {% endif %}                                  
                                </span>
                            </div>
                            <form method="post" action="" class="mt-4">

                                {{ form.hidden_tag() }}

                                <!-- Form -->
                                <div class="form-group mb-4">
                                    <label for="email">Usuario</label>
                                    <div class="input-group">
                                        <span class="input-group-text" id="basic-addon1"><span class="fas fa-user"></span></span>
                                        {{ form.username(class="form-control") }}
                                    </div>  
                                </div>
                                <!-- End of Form -->
                                <div class="form-group">
                                    <!-- Form -->
                                    <div class="form-group mb-4">
                                        <label for="password">Contraseña</label>
                                        <div class="input-group">
                                            <span class="input-group-text" id="basic-addon2"><span class="fas fa-unlock-alt"></span></span>
                                            {{ form.password(class="form-control", type="password") }}
                                        </div>  
                                    </div>
                                    <!-- End of Form -->
                                    <div class="d-flex justify-content-between align-items-center mb-4">
                                        <div class="form-check mb-0">
                                            <input class="form-check-input" type="checkbox" value="" id="remember">
                                            <label class="form-check-label mb-0" for="remember">
                                              Recuerdame
                                            </label>
                                        </div>
                                        <div><a href="{{ url_for('authentication_blueprint.register') }}" class="text-right">Registrarse</a></div>
                                    </div>
                                </div>
                                <div class="d-grid">
                                    <button type="submit" name="login" class="btn btn-primary">Ingresar</button>
                                </div>
                            </form>

                            <br />

                            <div class="d-flex justify-content-center align-items-center mt-4">
                                <span class="fw-normal">
                                    &copy; Marlon, set y milo asociados.         
                                </span>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </section>

    </main>

{% endblock content %}

<!-- Specific Page JS goes HERE  -->
{% block javascripts %}{% endblock javascripts %}

apps/templates/accounts/register.html
{% extends "layouts/base-fullscreen.html" %}

{% block title %} Sign UP {% endblock %} 

<!-- Specific Page CSS goes HERE  -->
{% block stylesheets %}{% endblock stylesheets %}

{% block content %}

    <main>

        {% include 'includes/preloader.html' %}

        <!-- Section -->
        <section class="min-vh-100 d-flex align-items-center section-image overlay-soft-dark" data-background="/static/assets/img/pages/form-image.jpg">
            <div class="container">
                <div class="row justify-content-center">
                    <div class="col-12 d-flex align-items-center justify-content-center">
                        <div class="signin-inner my-4 my-lg-0 bg-white shadow-soft border rounded border-gray-300 p-4 p-lg-5 w-100 fmxw-500">
                            <div class="text-center text-md-center mb-4 mt-md-0">
                                <h1 class="mb-0 h3">
                                    <a href="https://appseed.us/product/pixel-bootstrap/flask/" target="_blank">Nutriwizard</a> - Registrarse
                                </h1>
                                <br />
                                <span class="font-weight-normal">
                                    {% if msg %}
                                        {{ msg | safe }}
                                    {% else %}
                                        Añade tus credenciales
                                    {% endif %}                                  
                                </span>
                            </div>

                            {% if not success %}

                                <form method="post" action="" action="#">

                                    {{ form.hidden_tag() }}

                                    <div class="form-group mb-4">
                                        <label for="email">Usuario</label>
                                        <div class="input-group">
                                            <span class="input-group-text" id="basic-addon1"><span class="fas fa-user"></span></span>
                                            {{ form.username(class="form-control") }}
                                        </div>  
                                    </div>
                                    <!-- Form -->
                                    <div class="form-group mb-4">
                                        <label for="email">Correo</label>
                                        <div class="input-group">
                                            <span class="input-group-text" id="basic-addon3"><span class="fas fa-envelope"></span></span>
                                            {{ form.email(class="form-control", type="email") }}
                                        </div>  
                                    </div>
                                    <!-- End of Form -->
                                    <div class="form-group">
                                        <!-- Form -->
                                        <div class="form-group mb-4">
                                            <label for="password">Contraseña</label>
                                            <div class="input-group">
                                                <span class="input-group-text" id="basic-addon4"><span class="fas fa-unlock-alt"></span></span>
                                                {{ form.password(class="form-control", type="password") }}
                                            </div>  
                                        </div>
                                        <!-- End of Form -->
                                        <div class="d-flex justify-content-between align-items-center mb-4">
                                            <div class="form-check mb-0">
                                                <input class="form-check-input" type="checkbox" value="" id="remember">
                                                <label class="form-check-label mb-0" for="remember">
                                                Acepto terminos
                                                </label>
                                            </div>
                                            <div><a href="{{ url_for('authentication_blueprint.login') }}" class="text-right">Ingresar</a></div>
                                        </div>
                                    </div>
                                    <div class="d-grid">
                                        <button type="submit" name="register" class="btn btn-primary">Registrarse</button>
                                    </div>
                                </form>
                            
                            {% else %} 

                                <p class="mt-4 text-sm text-center">
                                    <a href="{{ url_for('authentication_blueprint.login') }}" class="btn btn-primary">Sign IN</a>
                                </p>
                            
                            {% endif %}

                            <br />

                            <div class="d-flex justify-content-center align-items-center mt-4">
                                <span class="fw-normal">
                                    &copy; Marlon, set y milo asociados.
                                </span>
                            </div>

                        </div>
                    </div>
                </div>
            </div>
        </section>

    </main>

{% endblock content %}

<!-- Specific Page JS goes HERE  -->
{% block javascripts %}{% endblock javascripts %}

apps/templates/home/blank.html
{% extends "layouts/layaout.html" %}

{% block title %} Grafica {% endblock %} 

<!-- Specific Page CSS goes HERE  -->
{% block stylesheets %}{% endblock stylesheets %}

{% block content %}

    <main>
        
        {% include 'includes/preloader.html' %}

        <!-- Hero -->
        <section class="section-header">
            <div class="container">
                <div class="row justify-content-center">
                    <div class="col-12 col-md-8 text-center">
                        <h1 class="display-2 mb-3">Distribución dieta</h1>
                        <div>
                            <canvas id="myChart"></canvas>
                          </div>
                          
                          <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
                          
                          <script>
                            let income_vs_expense_chart = new Chart(myChart, {
            type: 'pie',
            data: {
            labels: ['Carbohidratos', 'Proteinas', 'Grasas'],
                datasets: [{
                    label: "Gramos",
                    data: [247, 192, 85],
                    backgroundColor: ['#5DA5DA ', '#FAA43A', '#60BD68',
                        '#B276B2', '#E16851', '#FB8267'],

                    borderWidth: 1,
                    hoverBorderColor: "black",
                    hoverBorderWidth: 2,
                    hoverBackgroundColor: 'rgba(154, 245, 140)',
                    pointHoverRadius: 5
                }],
            },
            options: {
                    title: {
                        display: true,
                            text: "Income Vs Expenses",
                                fontSize: 20,
                    },
                    legend: {
                        position: "right",
                            labels: {
                            fontColor: "gray"
                        },
                        display: true,
                    },

                    elements: {
                        hitRadius: 3,
                    }
            }
        });
                          </script>
                    </div>
                </div>
            </div>
        </section>

    </main>

    {% include 'includes/footer.html' %}

{% endblock content %}

<!-- Specific Page JS goes HERE  -->
{% block javascripts %}

{% endblock javascripts %}

apps/templates/home/page-404.html
{% extends "layouts/base-fullscreen.html" %}

{% block title %} Error 404 {% endblock %} 

<!-- Specific Page CSS goes HERE  -->
{% block stylesheets %}{% endblock stylesheets %}

{% block content %}

    <main>

        {% include 'includes/preloader.html' %}

        <!-- Section -->
        <section class="min-vh-100 d-flex align-items-center section-image overlay-soft-dark" data-background="/static/assets/img/pages/form-image.jpg">
            <div class="container">
                <div class="row justify-content-center">
                    <div class="col-12 d-flex align-items-center justify-content-center">
                        <div class="signin-inner my-4 my-lg-0 bg-white shadow-soft border rounded border-gray-300 p-4 p-lg-5 w-100 fmxw-500">

                            <div class="text-center text-md-center mb-4 mt-md-0">
                                <h1 class="mb-0 h3">
                                    Error 404
                                </h1>
                                <br />
                                <p>
                                    Page not found
                                </p>
                            </div>

                            <div class="d-flex justify-content-center align-items-center mt-4">
                                <span class="fw-normal">
                                    <a href="/" class="fw-bold text-underline">Home</a> - Contact <a href="#" class="fw-bold text-underline">Support</a>.
                                </span>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </section>

    </main>

{% endblock content %}

<!-- Specific Page JS goes HERE  -->
{% block javascripts %}{% endblock javascripts %}

apps/templates/includes/footer-about.html
    <footer class="footer pb-6 bg-primary text-white pt-9 mt-n9">
        
            <hr class="my-5">
            <div class="row">
                <div class="col mb-md-0">
                    
                <div class="d-flex text-center justify-content-center align-items-center" role="contentinfo">
                    <p class="font-weight-normal font-small mb-0">
                        &copy; Marlon, set y milo asociados
                    </p>
                    </div>
                </div>
            </div>
        </div>
    </footer>
    

apps/templates/includes/navigation.html
    <header class="header-global">
        <nav id="navbar-main" aria-label="Primary navigation" class="navbar navbar-main navbar-expand-lg navbar-theme-primary headroom navbar-dark">
            <div class="container position-relative">
                <a class="navbar-brand me-lg-5" href="./index.html">
                    <img class="navbar-brand-dark" width="50" height="150" src="/static/assets/img/brand/wizard.png" alt="Logo ">
            
                </a>
                <div class="navbar-collapse collapse me-auto" id="navbar_global">
                    <div class="navbar-collapse-header">
                        <div class="row">
                            <div class="col-6 collapse-brand">
                                <a href="./index.html">
                                    <img src="/static/assets/img/brand/dark.svg" alt="Themesberg logo">
                                </a>
                            </div>
                            <div class="col-6 collapse-close">
                                <a href="#navbar_global" class="fas fa-times" data-bs-toggle="collapse" data-bs-target="#navbar_global" aria-controls="navbar_global" aria-expanded="false" title="close" aria-label="Toggle navigation"></a>
                            </div>
                        </div>
                    </div>
                    <ul class="navbar-nav navbar-nav-hover align-items-lg-center">
                        <li class="nav-item dropdown">
                            <a href="#" class="nav-link dropdown-toggle" id="frontPagesDropdown" aria-expanded="false" data-bs-toggle="dropdown">
                                Paginas
                                <span class="fas fa-angle-down nav-link-arrow ms-1"></span>
                            </a>
                            <div class="dropdown-menu dropdown-megamenu px-0 py-2 p-lg-4" aria-labelledby="frontPagesDropdown">
                                <div class="row">
                                    <div class="col-6 col-lg-4">
                                        <h6 class="d-block mb-3 text-primary">Paginas principal</h6>
                                        <ul class="list-style-none mb-4">
                                            <li class="mb-2 megamenu-item">
                                                <a class="megamenu-link" href="/about.html">Acerca de nosotros</a>
                                            </li>
                                            <li class="mb-2 megamenu-item">
                                                <a class="megamenu-link" href="/contact.html">Contactanos</a>
                                            </li>
                                            <li class="mb-2 megamenu-item">
                                                <a class="megamenu-link" href="/blank.html">Diagrama</a>
                                            </li>
                                        </ul>
                                    </div>
                                    <div class="col-6 col-lg-4">
                                        <h6 class="d-block mb-3 text-primary">Pagos</h6>
                                        <ul class="list-style-none mb-4">
                                            <li class="mb-2 megamenu-item">
                                                <a class="megamenu-link" href="/pagos.html">Planes</a>
                                            </li>
                                        </ul>
                                    </div>
                                    <div class="col-6 col-lg-4">
                                        <h6 class="d-block mb-3 text-primary">Usuario</h6>
                                        <ul class="list-style-none mb-4">
                                            <li class="mb-2 megamenu-item">
                                                <a class="megamenu-link" href="/sign-in.html">Ingresa</a>
                                            </li>
                                            <li class="mb-2 megamenu-item">
                                                <a class="megamenu-link" href="/sign-up.html">Registrate</a>
                                            </li>
                                        </ul>
                                    </div>
                                </div>
                            </div>
                        </li>
                        <li class="nav-item dropdown">
                            <a href="#" class="nav-link dropdown-toggle" id="componentsDropdown" aria-expanded="false" data-bs-toggle="dropdown">
                                Informacion
                                <span class="fas fa-angle-down nav-link-arrow ms-1"></span>
                            </a>
                            <div class="dropdown-menu dropdown-megamenu-md p-0" aria-labelledby="componentsDropdown">
                                <div class="row g-0">
                                    <div class="col-lg-6 bg-dark d-none d-lg-block me-0 me-3">
                                        <div class="px-0 py-3 text-center">
                                            <img src="/static/assets/img/megamenu_image.png" alt="Pixel Components">
                                        </div>
                                    </div>
                                    <div class="col ps-0 py-3">
                                        <ul class="list-style-none">

                                            <li><a class="dropdown-item" href="/ui-bootstrap-carousels.html">Fotografias</a></li>
                    
                                        </ul>
                                    </div>
                        
                                </div>
                            </div>
                        </li>
                        <li class="nav-item dropdown">
                            <a href="#" class="nav-link dropdown-toggle" data-bs-toggle="dropdown" id="supportDropdown" aria-expanded="false">
                                Ayuda
                                <span class="fas fa-angle-down nav-link-arrow ms-1"></span>
                            </a>
                            <div class="dropdown-menu dropdown-menu-lg" aria-labelledby="supportDropdown">
                                <div class="col-auto px-0">
                                    <div class="list-group list-group-flush">
                                        <a href="https://appseed.us/" target="_blank" 
                                           class="list-group-item list-group-item-action d-flex align-items-center p-0 py-3 px-lg-4">
                                            <span class="icon icon-sm"><span class="fas fa-microphone-alt"></span></span>
                                            <div class="ms-4">
                            
                                                <span class="small">Necesitas ayuda? Hablanos!</span>
                                            </div>
                                        </a>
                                    </div>
                                </div>
                            </div>
                        </li>
                    </ul>
                </div>
                <div class="d-flex align-items-center">
                    <a href="{{ url_for('authentication_blueprint.logout') }}"
                       class="btn btn-outline-gray-100 d-none d-lg-inline me-md-3"><span class="fas fa-sign-out-alt me-2"></span> Salir</a>
                </div>
            </div>
        </nav>
    </header>

apps/templates/includes/sidebar.html
<!-- NOT_IMPLEMENTED -->